### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by mlosonti** [n23daniel/redux-ecommerce-test#1]
this is shit

**Comment by n23daniel** [comment]
this is sparta

**Comment by n23daniel** [comment]
mishu pute

**Comment by mlosonti** [comment]
ba nu pute

**Comment by n23daniel** [comment]
blu blu

**Comment by n23daniel** [comment]
blob blob

**Comment by n23daniel** [comment]
a a a

**Comment by mlosonti** [comment]
da

2017-07-24 17:15 GMT+03:00 n23daniel <notifications@github.com>:

> a a a
>
>

**Comment by mlosonti** [comment]
ok



2017-07-24 17:20 GMT+03:00 Mihai Losonti <mihailosonti@gmail.com>:

> da
>
> 2017-07-24 17:15 GMT+03:00 n23daniel <notifications@github.com>:
>
>> a a a
>>
>>

**Comment by n23daniel** [comment]
am dat un reply

2017-07-24 17:51 GMT+03:00 mlosonti <notifications@github.com>:

> ok
>
>
>
> 2017-07-24 17:20 GMT+03:00 Mihai Losonti <mihailosonti@gmail.com>:
>
> > da
> >
> > 2017-07-24 17:15 GMT+03:00 n23daniel <notifications@github.com>:
> >
> >> a a a
> >>
> >>

**Comment by mlosonti** [comment]
nu mai da

2017-07-24 17:54 GMT+03:00 n23daniel <notifications@github.com>:

> am dat un reply
>
> 2017-07-24 17:51 GMT+03:00 mlosonti <notifications@github.com>:
>
> > ok
> >
> >
> >
> > 2017-07-24 17:20 GMT+03:00 Mihai Losonti <mihailosonti@gmail.com>:
> >
> > > da
> > >
> > > 2017-07-24 17:15 GMT+03:00 n23daniel <notifications@github.com>:
> > >
> > >> a a a
> > >>
> > >>

**Comment by mlosonti** [comment]
ba daniel

**Comment by n23daniel** [comment]
De pe mobil
